import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import SupabaseProviders from "@/providers/SupabaseProviders";
import UseProvider from "@/providers/UseProvider";
import ModalProvider from "@/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProviders>
         <UseProvider>
          <ModalProvider/>
         <Sidebar>{children}</Sidebar>
         </UseProvider>
        </SupabaseProviders>
      </body>
    </html>
  );
}
